### ISSUE TITLE
Desing Problems

### ISSUE THREAD

**Issue by davidwillianx** [wimbarelds/TimeCircles#89]
I've some design problems about TimeCircle, I dont know why but all the time that I include it  shows like this image below. May you give me some adivice?
![screenshot from 2015-02-26 09 59 49](https://cloud.githubusercontent.com/assets/5100338/6392365/bd536a56-bd9e-11e4-8f06-89b0070334b8.png)

**Comment by theonewolf** [comment]
Make sure you are including the TimeCircle.css file in your web page.

**Comment by wimbarelds** [comment]
It may be the css file, that could cause similar problems. If this is not the cause, could you provide a link to the/a page where this happens?

**Comment by barisnevres** [comment]
Hi Wim,
I have similar problem at http://berkaybesler.gomprojects.com/anasayfa :
![2016-11-15_16-16-36](https://cloud.githubusercontent.com/assets/23478178/20307110/94a53a52-ab46-11e6-9a96-7fb7237e824c.png)
Could you suggest something to me about this?
Thanks.

**Comment by wimbarelds** [comment]
Heya, the white line is caused by your stylesheet putting a border-bottom below h4 elements. You could fix this by adding this to your stylesheet:

```
#nextraceright .timecirclescontainer > div.time_circles > div > h4 {
    border-bottom-style: none;
}
```

Your CSS is also causing some other issues; so rather than adding this CSS it might be better to make your own css more specific and/or adding classes and ID's to the things you want to be styled.

**Comment by barisnevres** [comment]
Thanks. Your advice solved my problem.
I didn't define style for H4, but too many style definition coming from 3rd party component (Telerik). 
Thank you for your time.
